### ISSUE TITLE
ERROR: could not load library: Symbol not found: _ExecInitExprList

### ISSUE THREAD

**Issue by AliHaghani** [EnterpriseDB/mysql_fdw#176]
I get the following error after installation with PostgreSQL 9.6.10.

== 20170224094759 SetupMysqlFdw: migrating ====================================
-- execute("CREATE EXTENSION IF NOT EXISTS mysql_fdw;")
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::InternalError: ERROR:  could not load library "/usr/local/Cellar/postgresql@9.6/9.6.10/lib/mysql_fdw.so": dlopen(/usr/local/Cellar/postgresql@9.6/9.6.10/lib/mysql_fdw.so, 10): Symbol not found: _ExecInitExprList
  Referenced from: /usr/local/Cellar/postgresql@9.6/9.6.10/lib/mysql_fdw.so
  Expected in: /usr/local/opt/postgresql@9.6/bin/postgres
 in /usr/local/Cellar/postgresql@9.6/9.6.10/lib/mysql_fdw.so
: CREATE EXTENSION IF NOT EXISTS mysql_fdw;
/Library/Ruby/Gems/2.3.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:73:in `async_exec'
/Library/Ruby/Gems/2.3.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:73:in `block (2 levels) in execute'
/Library/Ruby/Gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
/Library/Ruby/Gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
/Library/Ruby/Gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
/Library/Ruby/Gems/2.3.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:72:in `block in execute'
/Library/Ruby/Gems/2.3.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block (2 levels) in log'
/Library/Ruby/Gems/2.3.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:611:in `block in log'
/Library/Ruby/Gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Library/Ruby/Gems/2.3.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:603:in `log'
/Library/Ruby/Gems/2.3.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:71:in `execute'
/Library/Ruby/Gems/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:849:in `block in method_missing'
/Library/Ruby/Gems/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:818:in `block in say_with_time'
/Library/Ruby/Gems/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:818:in `say_with_time'
/Library/Ruby/Gems/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:838:in `method_missing'
/Users/ali/GitHub/1001tl/db/migrate/20170224094759_setup_mysql_fdw.rb:3:in `up'
/Library/Ruby/Gems/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:795:in `exec_migration'
/Library/Ruby/Gems/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:776:in `block (2 levels) in migrate'
/Library/Ruby/Gems/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:775:in `block in migrate'
/Library/Ruby/Gems/2.3.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:408:in `with_connection'
/Library/Ruby/Gems/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:774:in `migrate'
/Library/Ruby/Gems/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:953:in `migrate'
/Library/Ruby/Gems/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1230:in `block in execute_migration_in_transaction'
/Library/Ruby/Gems/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1298:in `block in ddl_transaction'
/Library/Ruby/Gems/2.3.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
/Library/Ruby/Gems/2.3.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
/Library/Ruby/Gems/2.3.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
/Library/Ruby/Gems/2.3.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
/Library/Ruby/Gems/2.3.0/gems/activerecord-5.1.4/lib/active_record/transactions.rb:210:in `transaction'
/Library/Ruby/Gems/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1298:in `ddl_transaction'
/Library/Ruby/Gems/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1229:in `execute_migration_in_transaction'
/Library/Ruby/Gems/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1188:in `run_without_lock'
/Library/Ruby/Gems/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1140:in `block in run'
/Library/Ruby/Gems/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1317:in `with_advisory_lock'
/Library/Ruby/Gems/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1140:in `run'
/Library/Ruby/Gems/2.3.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1018:in `run'
/Library/Ruby/Gems/2.3.0/gems/activerecord-5.1.4/lib/active_record/railties/databases.rake:99:in `block (3 levels) in <top (required)>'
/Library/Ruby/Gems/2.3.0/gems/activerecord-5.1.4/lib/active_record/railties/databases.rake:84:in `block (3 levels) in <top (required)>'
/Library/Ruby/Gems/2.3.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/Library/Ruby/Gems/2.3.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Library/Ruby/Gems/2.3.0/gems/railties-5.1.4/lib/rails/command.rb:46:in `invoke'
/Library/Ruby/Gems/2.3.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

Would appreciate help, I followed the instructions as provided in the README. Installed mysql-connector-c via brew.

**Comment by AliHaghani** [comment]
This might've been happening after I switched PostgreSQL versions. Running the following command and then redoing the installation instructions fixed this for me.
`make clean USE_PGXS=1`
